apiVersion: apps/v1
kind: Deployment
metadata:
  name:  curl
  labels:
    name: curl
spec:
  replicas: 1
  selector:
    matchLabels:
      name: curl
  template:
    metadata:
      labels:
        name: curl
    spec:
      containers:
      - image:  rlmflores/curl-with-jq:20241005110518
        name: curl
        command: ["sleep"]
        args: ["infinity"]
